apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: fleet-gitops
  namespace: fleet-local
spec:
  repo: https://github.com/eddyg-github/fleet-gitops.git
  branch: main
  paths:
    - apps/filebrowser
